name: Database

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  migrations:
    name: Validate Migrations
    runs-on: ubuntu-latest
    container:
      image: php:8.5-fpm

    services:
      mysql:
        image: mysql:9.5
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: testing
          MYSQL_USER: laravel
          MYSQL_PASSWORD: hybridly
        options: >-
          --health-cmd="mysqladmin ping -phybridly"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/setup
        with:
          install-node: 'false'
          build-assets: 'false'
          run-migrations: 'false'

      - name: Run migrations
        run: php artisan migrate --force --verbose

      - name: Test migration rollback
        run: php artisan migrate:rollback --force --verbose

      - name: Re-run migrations
        run: php artisan migrate --force --verbose

      - name: Verify database schema
        run: php artisan migrate:status
