name: Code Style Checks

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Code Style Checks
    runs-on: ubuntu-latest
    container:
      image: php:8.5-fpm

    services:
      mysql:
        image: mysql:9.5
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: testing
          MYSQL_USER: laravel
          MYSQL_PASSWORD: hybridly
        options: >-
          --health-cmd="mysqladmin ping -phybridly"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/setup

      - name: Run database migrations
        run: php artisan migrate --force

      - name: Generate IDE Helper files
        run: |
          mkdir -p helpers
          php artisan ide-helper:eloquent
          php artisan ide-helper:generate
          php artisan ide-helper:meta
          php artisan ide-helper:models -M

      - name: Run Laravel Pint
        run: php ./vendor/bin/pint --test

      - name: Cache PHPStan results
        uses: actions/cache@v4
        with:
          path: storage/phpstan
          key: ${{ runner.os }}-phpstan-${{ github.sha }}
          restore-keys: ${{ runner.os }}-phpstan-

      - name: Run PHPStan
        run: php ./vendor/bin/phpstan analyze --memory-limit=2G

      - name: Run ESLint
        run: pnpm eslint . --max-warnings=0

      - name: Run vue-tsc
        run: pnpm vue-tsc --noEmit
