name: Tests

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    name: ${{ matrix.testsuite }} Tests
    runs-on: ubuntu-latest
    container:
      image: php:8.5-fpm

    strategy:
      fail-fast: false
      matrix:
        testsuite:
          - Feature
          - Unit
          - Architecture

    services:
      mysql:
        image: mysql:9.5
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: testing
          MYSQL_USER: laravel
          MYSQL_PASSWORD: hybridly
        options: >-
          --health-cmd="mysqladmin ping -phybridly"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

      redis:
        image: redis:8.0
        options: >-
          --health-cmd="redis-cli ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/setup
        with:
          run-migrations: 'true'

      - name: Run ${{ matrix.testsuite }} tests
        run: php artisan test --order-by random --testsuite=${{ matrix.testsuite }}
